### ISSUE TITLE
Broken on win32

### ISSUE THREAD

**Issue by petemoore** [mholt/archiver#152]
## What version of the package or command are you using?
`bfece90dc3bb7199e8a397a27eb267a6cdd9589c`

## What are you trying to do?
Extract [Git-2.11.0.3-32-bit.tar.bz2](https://github.com/git-for-windows/git/releases/download/v2.11.0.windows.3/Git-2.11.0.3-32-bit.tar.bz2) on Windows 7 32 bit edition

## What steps did you take?
See [task definition](https://tools.taskcluster.net/groups/Wz1hd0EJRMCgO06WipokRQ/tasks/Ho2J-QK4Reay9mnUEDLXiw/details):

1) Downloaded [Git-2.11.0.3-32-bit.tar.bz2](https://github.com/git-for-windows/git/releases/download/v2.11.0.windows.3/Git-2.11.0.3-32-bit.tar.bz2) as `git.tar.bz2`

2) Extracted it successfully with archiver version 2.1:

```
archiver.exe open git.tar.bz2 git
```

3) Built from master branch revision `bfece90dc3bb7199e8a397a27eb267a6cdd9589c`
4) Tried to extract with version 3 `arc unarchive git.tar.bz2 git2`

## What did you expect to happen, and what actually happened instead?

I expected the extraction to be successful. But I got [errors](https://taskcluster-artifacts.net/Ho2J-QK4Reay9mnUEDLXiw/0/public/logs/live_backing.log):

```
Z:\task_1551972425>arc unarchive git.tar.bz2 git2 
2019/03/07 15:37:07 [ERROR] Reading file in tar archive: git2\git\mingw32\bin\git-upload-archive.exe: making hard link for: link git2\git\mingw32\bin\git-upload-archive.exe\mingw32\bin\git-receive-pack.exe git2\git\mingw32\bin\git-upload-archive.exe: The system cannot find the path specified.
2019/03/07 15:37:10 [ERROR] Reading file in tar archive: git2\git\mingw32\libexec\git-core\git.exe: making hard link for: link git2\git\mingw32\libexec\git-core\git.exe\mingw32\bin\git.exe git2\git\mingw32\libexec\git-core\git.exe: The system cannot find the path specified.
2019/03/07 15:37:10 [ERROR] Reading file in tar archive: git2\git\mingw32\libexec\git-core\git-add.exe: making hard link for: link git2\git\mingw32\libexec\git-core\git-add.exe\mingw32\bin\git-receive-pack.exe git2\git\mingw32\libexec\git-core\git-add.exe: The system cannot find the path specified.
2019/03/07 15:37:10 [ERROR] Reading file in tar archive: git2\git\mingw32\libexec\git-core\git-am.exe: making hard link for: link git2\git\mingw32\libexec\git-core\git-am.exe\mingw32\bin\git-receive-pack.exe git2\git\mingw32\libexec\git-core\git-am.exe: The system cannot find the path specified.
2019/03/07 15:37:10 [ERROR] Reading file in tar archive: git2\git\mingw32\libexec\git-core\git-annotate.exe: making hard link for: link git2\git\mingw32\libexec\git-core\git-annotate.exe\mingw32\bin\git-receive-pack.exe git2\git\mingw32\libexec\git-core\git-annotate.exe: The system cannot find the path specified.
2019/03/07 15:37:10 [ERROR] Reading file in tar archive: git2\git\mingw32\libexec\git-core\git-apply.exe: making hard link for: link git2\git\mingw32\libexec\git-core\git-apply.exe\mingw32\bin\git-receive-pack.exe git2\git\mingw32\libexec\git-core\git-apply.exe: The system cannot find the path specified.
2019/03/07 15:37:10 [ERROR] Reading file in tar archive: git2\git\mingw32\libexec\git-core\git-archive.exe: making hard link for: link git2\git\mingw32\libexec\git-core\git-archive.exe\mingw32\bin\git-receive-pack.exe git2\git\mingw32\libexec\git-core\git-archive.exe: The system cannot find the path specified.
.....
```

## How do you think this should be fixed?
Presumably this is a regression, since we could extract the same .tar.bz file on Windows 7 32 bit edition using archiver 2.1.

## Please link to any related issues, pull requests, and/or discussion

* [Mozilla bug 1533402](https://bugzil.la/1533402) 

## Bonus: What do you use archiver for, and do you find it useful?

We import the go library at Mozilla in the worker that runs most of Mozilla's CI tasks.

**Comment by mholt** [comment]
Thanks for the detailed report! Reproducible on Mac too.

**Comment by mholt** [comment]
Should be fixed in #171

**Comment by petemoore** [comment]
I think this issue is still present, see https://github.com/mholt/archiver/pull/171#issuecomment-588129903.

Many thanks!
